* About
  This code is under development in my nightly hours.

  I'm using this code for my android development with a lot of other
  tools, so it works but too few functionality. Currently, I'm working
  on porting =jde-import-*= functions, but not for porting purpose,
  cause I'm curious about how cedet and jde works, that is all.
  
* Info
  This code is still bad structured but I found =ede-x-android.el= and
  =x-android.el= are easy to read and use.

  Other files are almost snippets from various projects (jde, ajc).

  Try to look at wiki to see how to use this tool.

* What has been changed (or added) to bzr version
  - You don't need to revisit AndroidManifest.xml to open project.
  - In x-android.el all functions related to android projects
  - class import functions 
  - Finding sources/libraries/files recursively across linked
    libraries that found in project.properties file
  - New targets like: "debug clean install"
  - Added 2 keybindings to open: nine-patch editor or gui builder
  
* License
  The same as cedet or emacs, I guess.
