;;
;; This file contains utils to parse database generated by
;; https://github.com/m039/clj-parse-android
;;

(require 'x-android-db)


(defun x-android-db-parser/select-database ( database-path )
  (x-android-db/start-sqlite-process)
  (x-android-db/send-command (x-android-db/command/select-database database-path)))

(defun x-android-db-parser/enitity-query ( where )
  (format "SELECT name,simple_name,methods,enclosing_class__name FROM class WHERE %s" where))

(defun x-android-db-parser/query/interfaces ()
  (let ((query (x-android-db-parser/enitity-query (format "is_interface = 1"))))
    (x-android-db/send-command (x-android-db/command/query query))))

(defun x-android-db-parser/get/name ( entity )
  (nth 0 entity))

(defun x-android-db-parser/get/simple_name ( entity )
  (nth 1 entity))

(defun x-android-db-parser/get/methods ( entity )
  (nth 2 entity))

(defun x-android-db-parser/get/enclosing_class ( entity &optional return-entity )
  (let ((name (nth 3 entity)))
    (if (null return-entity)
        name
      (let ((query (x-android-db-parser/enitity-query (format "name = '%s'" name))))
        (car (x-android-db/send-command (x-android-db/command/query query)))))))


(defun x-android-db-parser/extract/simple_name ( result )
  (mapcar (lambda (l) (nth 1 l)) result))

(defun x-android-db-parser/extract/name ( result )
  (mapcar (lambda (l) (nth 0 l)) result))


(defun x-android-db-parser/filter ( predicate coll )
  (delq nil (mapcar predicate coll)))


(defun x-android-db-parser/filter/simple_name ( simple-name coll )
  "Filter collection (or result from query) by simple_name column."
  (x-android-db-parser/filter (lambda (l)
                                (let ((sn (x-android-db-parser/get/simple_name l)))
                                  (when (string= sn simple-name)
                                    l))) coll))


(defun x-android-db-parser/filter/name ( name coll )
  "Filter collection (or result from query) by name column."
  (x-android-db-parser/filter (lambda (l)
                                (let ((n (x-android-db-parser/get/name l)))
                                  (when (string= n name)
                                    l))) coll))


(defun x-android-read-interface ()
  (interactive)
  (let* ((interfaces (x-android-db-parser/query/interfaces))
         (simple-names (x-android-db-parser/extract/simple_name interfaces))
         (selected-interfaces (x-android-db-parser/filter/simple_name
                               (completing-read "Select the interface: " simple-names)
                               interfaces)))

    (when (> (length selected-interfaces) 1)
      (let ((names (x-android-db-parser/extract/name selected-interfaces)))
        (setq selected-interfaces (x-android-db-parser/filter/name
                                   (completing-read "Correct the selection: " names)
                                   interfaces))))

    (car selected-interfaces)))

(defun x-android-db-parser/read-interface ( &optional for-yas )
  (interactive)
  (let ((global-arg-count 1))
    (flet ((find-return-type ( method )
                             (with-temp-buffer
                               (insert method)

                               (goto-char (point-min))
                               (search-forward "public" nil t)

                               (forward-word)

                               (let ((end (point)))
                                 (backward-word)
                                 (buffer-substring (point) end))))

           (insert-args-in-method (method)
                                  (let ((arg-count 0)
                                        start
                                        end)
                                    (with-temp-buffer
                                      (insert method)
                                      (goto-char (point-min))

                                      (search-forward "(" nil t)
                                      (setq start (point))

                                      (search-forward ")" nil t)
                                      (setq end (point))

                                      (if (<= (- end start) 1)
                                          ;; no arguments
                                          (buffer-string)
                                        ;; there is some arguments
                                        (goto-char start)
                                        
                                        (forward-word)
                                        (insert (if for-yas
                                                    (format " ${%d:arg%d}" global-arg-count arg-count)
                                                  (format " arg%d" arg-count)))
                                        (setq arg-count (+ arg-count 1))
                                        (setq global-arg-count (+ global-arg-count 1))

                                        (while (search-forward "," nil t)
                                          (forward-word)
                                          (insert (if for-yas
                                                    (format " ${%d:arg%d}" global-arg-count arg-count)
                                                  (format " arg%d" arg-count)))
                                          (setq arg-count (+ arg-count 1)))
                                        (setq global-arg-count (+ global-arg-count 1))
                                        
                                        (buffer-string)))))
           )

      (let ((interface (x-android-read-interface)))
        (unless (null interface)
          (let ((simple-name (x-android-db-parser/get/simple_name interface))
                (name (x-android-db-parser/get/name interface))
                (methods (x-android-db-parser/get/methods interface))
                (enclosing-class (x-android-db-parser/get/enclosing_class interface t))
                (start (point)))

            (if (null enclosing-class)
                (setq enclosing-class "")
              (setq enclosing-class (format "%s." (x-android-db-parser/get/simple_name enclosing-class))))
            
            (format (if for-yas
                        "new %s%s() {\n%s};"
                      "new %s%s() {\n%s};$0")
                    
                    enclosing-class
                    simple-name
                    (with-temp-buffer
                      (dolist (m (split-string methods "\n"))
                        (let ((return-type (find-return-type m)))
                          (insert (format (cond ((let ((first-letter (aref return-type 0)))
                                                   (when (= first-letter (upcase first-letter))
                                                     t))
                                                 "@Override\n%s {\nreturn null;\n}\n")

                                                ((string= return-type "boolean")
                                                 "@Override\n%s {\nreturn false;\n}\n")

                                                ((string= return-type "int")
                                                 "@Override\n%s {\nreturn 0;\n}\n")

                                                ((string= return-type "float")
                                                 "@Override\n%s {\nreturn 0.0f;\n}\n")

                                                (t
                                                 "@Override\n%s {\n}\n"))
                                          (insert-args-in-method m)))))
                      (buffer-string)))
            ))))))

(defun x-android-new-interface ()
  (interactive)
  (let ((start (point)))
    (insert (x-android-db-parser/read-interface))
    (indent-region start (point))))

(defun x-android-new-interface-yas ()
  (interactive)
  (let ((start (point)))
    (yas/expand-snippet (x-android-db-parser/read-interface t))
    (indent-region start (point))))
